# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_mail', models.EmailField(max_length=100)),
                ('user_content', models.TextField()),
                ('password', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='пароль')),
            ],
            options={
                'verbose_name': 'юзер',
                'verbose_name_plural': 'юзеры',
            },
        ),
    ]
