# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-09 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200309_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pol', models.CharField(max_length=100, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'пол',
                'verbose_name_plural': 'пол',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('pol', models.CharField(blank=True, choices=[('m', 'мужской'), ('g', 'женский')], max_length=100, verbose_name='пол')),
                ('statstar', models.CharField(blank=True, choices=[('a', 'в отношениях'), ('b', 'свободен')], max_length=100, verbose_name='статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профиль пользователя',
            },
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Book', verbose_name='книга'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь1'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='должен вернуть'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=200, verbose_name='отпечаток'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Поддержка'), ('o', 'Взаймы'), ('a', 'Доступный'), ('r', 'Зарезервированна')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
